### ISSUE TITLE
运行Server0.9.1后登录异常

### ISSUE THREAD

**Issue by liyong1983** [IKende/Bumblebee#11]
运行登录成功后，跳转到index页面然后就又跳回login页面 
windows系统 谷歌浏览器 （71.0.3578.98）

**Comment by IKende** [comment]
@liyong1983 
浏览器有禁用cookie吗？

**Comment by liyong1983** [comment]
Cookie没有禁用 神奇的是我用127.0.0.1是可以登录的 localhost就不行

**Comment by IKende** [comment]
按道理不存在这情况，一般跳转是websocket connect的时候cookie相关验证无效

**Comment by lonelyxmas** [comment]
docker pull ikende/beetlex_gateway
FireFox 66.0.5 运行登录成功后，跳转到index页面然后就又跳回login页面,
Chrome 73.0.3683.86 正常

**Comment by IKende** [comment]
可能是FireFox 在创建websocket的时候，没有带上cookie头信息，迟下改成默认使用http，而不是websocket
