### ISSUE TITLE
Requested事件接收和返回数据的问题

### ISSUE THREAD

**Issue by yuanqinglin1** [IKende/Bumblebee#13]
1.Requested事件，请问如何获取请求api返回的数据？
2.Requested事件，请问如何对api返回的数据重新封装返回前端？

**Comment by IKende** [comment]
@yuanqinglin1 
暂没提供这样的事件，`Requested`事件是已经响应完成，主要用于日志和跟踪用。
能否说一下这样做的需求情况

**Comment by yuanqinglin1** [comment]
您好，主要是考虑到兼容和规范问题。
兼容：之前没有对数据接收和返回进行规范，程序人员风格不统一，甚至导致返回失效。
规范：想利用网关对返回前端的对象进行重新封装。
请问是否有可能实现的解决方案？




------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 晚上9:37
收件人: "IKende/Bumblebee"<Bumblebee@noreply.github.com>;
抄送: "'要'"<837258978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IKende/Bumblebee] Requested事件接收和返回数据的问题 (#13)




@yuanqinglin1
 暂没提供这样的事件，Requested事件是已经响应完成，主要用于日志和跟踪用。
 能否说一下这样做的需求情况

**Comment by IKende** [comment]
@yuanqinglin1 
其实网关只负责网络流的处理，这种拆解分析消息体再拼装对性能的影响还是比较大的，
可以尝试了解一下`RequestAgent`类的`ResponseBody`方法，这个方法是负责http消息体转发。

**Comment by yuanqinglin1** [comment]
明白。
根据给我的提示，我已经可以获取请求的Stream数据，
但想获取服务API返回的数据，并进行重新封包返回前端 
还是找不到方法，请问有实现的思路吗？

**Comment by IKende** [comment]
@yuanqinglin1 
把流中的数据read to bytes后根据自己实际情况进行处理，然后把最终结果转成bytes写回到对应响应的流中。

**Comment by yuanqinglin1** [comment]
输入正确的账号密码，从__admin/index闪退到login.html，
请问这是什么问题？


------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午5:41
收件人: "IKende/Bumblebee"<Bumblebee@noreply.github.com>;
抄送: "'要'"<837258978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IKende/Bumblebee] Requested事件接收和返回数据的问题 (#13)




@yuanqinglin1
 把流中的数据read to bytes后根据自己实际情况进行处理，然后把最终结果转成bytes写回到对应响应的流中。

**Comment by yuanqinglin1** [comment]
请问urlroute设置home1，但访问却没有跳转，这是什么问题？




------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午5:41
收件人: "IKende/Bumblebee"<Bumblebee@noreply.github.com>;
抄送: "'要'"<837258978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IKende/Bumblebee] Requested事件接收和返回数据的问题 (#13)




@yuanqinglin1
 把流中的数据read to bytes后根据自己实际情况进行处理，然后把最终结果转成bytes写回到对应响应的流中。

**Comment by IKende** [comment]
@yuanqinglin1 
使用正则表达式来匹配

**Comment by yuanqinglin1** [comment]
关于网关地址9090登陆不上，有闪退的情况，我试过重启电脑，是可以的，但用了一段时间后就登陆不上了，目录下文件除了只修改过Gateway.json外，并无其他修改。
请问这种问题应该怎么发现问题并处理？




------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年5月2日(星期四) 晚上9:47
收件人: "IKende/Bumblebee"<Bumblebee@noreply.github.com>;
抄送: "'要'"<837258978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IKende/Bumblebee] Requested事件接收和返回数据的问题 (#13)




@yuanqinglin1
 使用正则表达式来匹配
