### ISSUE TITLE
ValidateRPS bug

### ISSUE THREAD

**Issue by eddyyuen** [IKende/Bumblebee#15]
>  internal bool ValidateRPS()
>             {
>                 if (MaxRPS == 0)
>                     return true;
>                 long now = TimeWatch.GetElapsedMilliseconds();
>                 if (now - mLastTime >= 1000)
>                     return true;
>                 return mRPS < MaxRPS;
>             }
> 
When MaxRPS=1 ,it allways return False.
It should be :

> return mRPS <= MaxRPS;

**Comment by IKende** [comment]
thanks
