### ISSUE TITLE
How can I use reroute link like Ocelot

### ISSUE THREAD

**Issue by huanbd** [IKende/Bumblebee#19]
Hi IKende, thanks for your project. It's impress when compare to Ocelot. But I like reroute feature of Ocelot. So Bumblebee have that ? How can I use it.

**Comment by huanbd** [comment]
Hi IKende, 
In a tab Routes in page manager I can only add route for gate, but I can't define a route for an downstream api
Ex: link upstream: /api/data1
link downstream: /home/data

**Comment by IKende** [comment]
url rewrite is not support

**Comment by IKende** [comment]
Using [BeetleX.Bumblebee.UrlRewrite](https://www.nuget.org/packages/BeetleX.Bumblebee.UrlRewrite/) plugin support this feature
