### ISSUE TITLE
添加Url重写插件

### ISSUE THREAD

**Issue by IKende** [IKende/Bumblebee#20]
添加url重写插件

**Comment by IKende** [comment]
update 1.1.8

**Comment by eddyyuen** [comment]
我们有些业务需要根据Request的数据进行rewrite（例如ABTest进行分流，部分人员调用新接口）
能不能增加设置URL的方法，例:
SetRewriteUrl(rewriteUrl){
this.IsRewrite = true;
this.SourceUrl = Url;
this.SourceBaseUrl = BaseUrl;
this.SourcePath = Path;
Url  = rewriteUrl;
}。
现在AgentRequesting用这种方法来改写Url：
` var url = e.Request.GetType().GetProperty("Url");  ` 
`url.SetValue(e.Request, RewriteUrl, null);`

但是这样在统计URL的时候显示的是Rewrite后的URL。
