### ISSUE TITLE
能否在插件中动态设置RewriteUrl

### ISSUE THREAD

**Issue by eddyyuen** [IKende/Bumblebee#26]
我们有些业务在Requesting时需要根据Request的数据进行rewrite（例如ABTest进行分流，部分人员调用新接口）
能不能增加设置URL的方法，例:
SetRewriteUrl(rewriteUrl){
this.IsRewrite = true;
this.SourceUrl = Url;
this.SourceBaseUrl = BaseUrl;
this.SourcePath = Path;
Url  = rewriteUrl;
}。
现在AgentRequesting用这种方法来改写Url：
` var url = e.Request.GetType().GetProperty("Url");  ` 
`url.SetValue(e.Request, RewriteUrl, null);`

但是这样在统计URL的时候显示的是Rewrite后的URL。

**Comment by IKende** [comment]
1.1.9的httprequest已提供UrlRewriteTo方法

**Comment by eddyyuen** [comment]
> 1.1.9的httprequest已提供UrlRewriteTo方法

已更新测试成功，谢谢
