### ISSUE TITLE
如何不统计资源文件的访问

### ISSUE THREAD

**Issue by ibcla** [IKende/Bumblebee#31]
Home面板上的Total (Top 10)会统计css js。如何过滤这些请求？因为网站每天有近百万的访问量我需要查看哪个页面使用的最多

**Comment by IKende** [comment]
暂不支持，后面会把这个调整成选择监控的url,毕竟如果有数万或更多url每次都这样刷新统计会有问题。

**Comment by IKende** [comment]
最好的方案是了解一下源码，写个responsed插件自己记录数据进行统计。

**Comment by IKende** [comment]
在新版中添加了`SetStatisticsExts`方法可以配置
