### ISSUE TITLE
使用wrk压力测试时，超过500连接就会出现500错误

### ISSUE THREAD

**Issue by eddyyuen** [IKende/Bumblebee#32]
网关测试：
> wrk -t10 -c500 -d30s -T30s http://127.0.0.1:9000/user/getuserinfo
Running 30s test @ http://127.0.0.1:9000/user/getuserinfo
  10 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    43.87ms   51.35ms 781.09ms   95.91%
    Req/Sec     1.32k   425.11     3.94k    73.91%
  395668 requests in 30.09s, 95.09MB read
  Socket errors: connect 0, read 18217, write 0, timeout 0
Requests/sec:  13150.42
Transfer/sec:      3.16MB

网关调用的webapi接口的测试，api本身没问题
> $ wrk -t10 -c500 -d30s -T30s http://127.0.0.1:9050/user/getuserinfo
Running 30s test @ http://127.0.0.1:9050/user/getuserinfo
  10 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    51.80ms  267.11ms  11.01s    97.92%
    Req/Sec     4.26k     2.56k   18.50k    76.59%
  1260011 requests in 30.10s, 258.35MB read
Requests/sec:  41861.31
Transfer/sec:      8.58MB

出错日志（详细日志写不了，会导致并发下降就不会出错）：
> [2019/11/7 下午7:47:37] [Error] session 127.0.0.1:34530@17972 error 127.0.0.1:34530 send data completed process handler error Object reference not set to an instance of an object.!@Object reference not set to an instance of an object.
   at BeetleX.FastHttpApi.HttpApiServer.SendCompleted(ISession session, SocketAsyncEventArgs e)
   at BeetleX.TcpServer.SendCompleted(SocketAsyncEventArgs e)

**Comment by IKende** [comment]
这个错误会让人误解，在新版中已经调成`Warring`。主要触发的情况是发送完成后处理一些状态正好连接断开了引发了，实际上对服务没有影响。
