### ISSUE TITLE
页面乱码

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#36]
![image](https://user-images.githubusercontent.com/3090191/69913734-aa0e9400-1476-11ea-9618-251058e8ec8e.png)
![image](https://user-images.githubusercontent.com/3090191/69913739-c27eae80-1476-11ea-8b8c-7579635eebe7.png)

**Comment by IKende** [comment]
尝试更新到最新的`Bumblebee`和`Configuration`,看样子你那个是旧的，新版本主界面已经不是这样。
![image](https://user-images.githubusercontent.com/2564178/69925651-4161fe80-14ec-11ea-9dd3-be92a02a365f.png)
