### ISSUE TITLE
插件Log db 报错

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#37]
![image](https://user-images.githubusercontent.com/3090191/70198151-001a5a80-1749-11ea-81a8-88275ddd8e87.png)

就改了数据库名称。3天偶尔出现一次

**Comment by IKende** [comment]
`fasthttpapi`在生成requestid序号的时候是存在一些问题，当达到1kw的子序号情况可能会产程这错误。
还有gateway.json在复制到其他服务时注意要把`InstanceID`这个清除

**Comment by nodyang** [comment]
Gateway 26433376290340866 ::1 GET /favicon.ico request increment event error Object reference not set to an instance of an object.@   at Bumblebee.Gateway.RequestIncrementCompleted(HttpRequest request, Int32 code, Int64 time, ServerAgent server 中午重启下。私活起不来

**Comment by nodyang** [comment]
{
    "Limit": 100,
    "DisabledTime": 100,
    "CleanTime": 1800,
    "WhiteList": []
}这个default_ip_concurrent_limits 去了就好了
