### ISSUE TITLE
插件【default_ip_concurrent_limits】 重启报错 

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#39]
1  服务器迁移=>centOS 启动报错
2 配置的 default_ip_concurrent_limits {
    "Limit": 100,
    "DisabledTime": 1000,
    "CleanTime": 1800,
    "WhiteList": [
     
    ]
}
3 页面点击不动
4 
![image](https://user-images.githubusercontent.com/3090191/70308252-c8450d00-1845-11ea-8ce7-a6ca2caf2460.png)
目前只能关闭。
5 上次提的数据库日志偶尔还是主键冲突。

Gateway 26435002405224848 ::1 GET /__system/bumblebee/index.html process error Method not found: 'Void Bumblebee.Gateway.Incremen
tRequestCompleted(BeetleX.FastHttpApi.HttpRequest, Int32, Int64, Bumblebee.Servers.ServerAgent)'.@   at Bumblebee.ConcurrentLimits.IPConcurrentLimit
s.Execute(EventRequestingArgs e)
   at Bumblebee.Plugins.Pluginer.Requesting(HttpRequest request, HttpResponse response)
   at Bumblebee.Gateway.OnRequest(Object sender, EventHttpRequestArgs e)
![image](https://user-images.githubusercontent.com/3090191/70308033-6684a300-1845-11ea-8193-51e7cc780311.png)

**Comment by IKende** [comment]
看样子Bumblebee版本比较低没有`Incremen
tRequestCompleted`方法，用最新的版本或自己编译最新版本

**Comment by nodyang** [comment]
我用的就是nuget 最新的版本

**Comment by nodyang** [comment]
源码编译 也是出错的

**Comment by IKende** [comment]
看样子是有些问题，新的版本暂只能停用这个组件。估计要等下一个Bumblebee版本更新，才会一起更新。

**Comment by nodyang** [comment]
好的 期待
