### ISSUE TITLE
请教一个log error 问题

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#40]
![image](https://user-images.githubusercontent.com/3090191/70308978-6dacb080-1847-11ea-86b4-d9d30b6cbd62.png)
晚上存在这样大量的请求。是我们被攻击了吗 我看IP 还有国外的。

**Comment by IKende** [comment]
组件并没有屏蔽协议解释类的错误，只要对方提供的协议内容有问题都会报异常并记录

**Comment by nodyang** [comment]
明白了。 因为现在的下游系统才有验证。。
