### ISSUE TITLE
我想写一个路由聚合的插件，不知道有没有可行性

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#42]
因为之前用的是ocelot，使用了路由聚合， 并且已经在使用中，但是现在希望使用这个网关，所以希望也能支持路由聚合，

那么，我想以插件的形式实现，是否可行呢

**Comment by IKende** [comment]
可否描述一下`路由聚合`的功能需求场景

**Comment by wwping** [comment]
是这样的，我们有多个服务，并且是前后端分离的

**用户服务**   **管理员服务**   **付费产品服务**

在用户登录成功后使用   **付费产品服务**  ，
普通用户需要购买才可使用， 但是管理员是可以直接使用的，

这样的话，我希望能 通过 一个api ，比如  /api/user/logininfo   就可以取到  用户信息+管理员信息+付费信息，这是一个很方便的功能。

**Comment by IKende** [comment]
你描述的需求也只是验证问题，可以编写验证插件或用组件的jwt插件。
我想了解一下转发规则的场景

**Comment by wwping** [comment]
### 网关地址 
 http://localhost:8081

#### 用户信息api   
http://localhost:5000/api/user/info
返回
`
{
islogin:true
}
`
#### 管理员信息api   
http://localhost:5001/api/admin/info
返回
`
{
  isadmin:true
}
`
#### 付费信息api   
http://localhost:5002/api/pay/info
返回
`
{
  paylist:["p1","p2"]
}
`
### 需求
我希望能通过  http://localhost:8081/api/user/logininfo
只发送一次请求就得到 
`
 {
    islogin:true
    isadmin:true,
    paylist:["p1","p2"]
}
`
或者得到
`
 {
    user:{islogin:true}
    admin:{isadmin:true,}
    pay:{paylist:["p1","p2"]}
}
`

## 类似于 ocelot的 
[https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html](url)

**Comment by IKende** [comment]
这种根据规则转发到不同服务器的不需要编写插件，可以在路由中配置样规则即可,
`^/api/admin/.*`,`^/api/play/.*`,`^/api/user/.*`

大概如下:
![image](https://user-images.githubusercontent.com/2564178/71171682-559e4d80-2299-11ea-83fb-caff603d9439.png)

**Comment by wwping** [comment]
不是这样的，不知你有没有了解过ocelot的路由聚合，就是上面发的那个链接

## 通过请求一个api获得多个api的结果

**Comment by IKende** [comment]
这种的确是可以通过扩展IRequestingHandler来完成,不过写起来最好了解一下组件代码，以下参考代码,主要思路是拦载某个请求的路径，取消往下执行并自己response需要的内容（这个内容根据你自己的需要进行不同httpclient请求后整合）
``` csharp
 [Bumblebee.Plugins.RouteBinder(RouteUrl = "^/xxx.*", ApiLoader = false)]
    public class StaticResourcePlugins : Bumblebee.Plugins.IRequestingHandler
    {
        public string Name => "xxx_Aggregator ";

        public string Description => "Aggregator";

        public PluginLevel Level => PluginLevel.None;

        public void Execute(EventRequestingArgs e)
        {
           public void Execute(EventRequestingArgs e)
        {
           e.Response.Result(data)
            e.Cancel = true;
            e.ResultType = ResultType.Completed;
        }
        }

        public void Init(Gateway gateway, Assembly assembly)
        {
            
        }

        public void LoadSetting(JToken setting)
        {

        }

        public object SaveSetting()
        {
            return null;
        }
    }
```

**Comment by wwping** [comment]
有没有一些内置的性能比较好的请求方法呢，
如果我自己 new HttpClient 来请求多个api，会不会有性能问题呢

**Comment by IKende** [comment]
其实这样做只能说需求的必要性，对性能而言语基本无法处理好；即使自己手动写轻量的httpclien也只能解决很少的性能问题，这种字符类的聚合会产生很多大的`string`对GC来说很严重。

**Comment by wwping** [comment]
-

**Comment by wwping** [comment]
我拿项目里的那个 BumblebeeVSOcelot 项目试着运行了一下， 
我电脑是 I5 8400   16G DDR4  ，是不是我打开的方式不太对
![1](https://user-images.githubusercontent.com/10977033/71174773-ef1d2d80-22a0-11ea-93de-2d0b81b1ec4a.png)

**Comment by IKende** [comment]
建议发布后，再分机部署测试

**Comment by IKende** [comment]
增加聚合插件
http://doc.beetlex.io/#2910d44177674035af151b636c5a0c29

**Comment by wwping** [comment]
> 增加聚合插件
> http://doc.beetlex.io/#2910d44177674035af151b636c5a0c29

非常感谢，立马试试
