### ISSUE TITLE
out of max connections!

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#48]
![image](https://user-images.githubusercontent.com/3090191/71717001-95486600-2e51-11ea-9032-8bc071713bbf.png)
210是网管服务器  
![image](https://user-images.githubusercontent.com/3090191/71717051-c0cb5080-2e51-11ea-9cad-d64b93486bb1.png)

**Comment by nodyang** [comment]
不知道啥意思。今天日志一直在报这个警告

**Comment by IKende** [comment]
网关依赖的`FastHttpApi`需要配置更大的连接数,默认配置应该是2K，自己根据情况配置。
http://doc.ikende.com/#c6d82c8e677f43cfa1127f32c308caa1

**Comment by nodyang** [comment]
我一直觉得2K对我来说够用。。这个是新系统。还没有多少数据量 就是内部测试。网管连着一个业务系统。下午出现了 访问不了  查看日志 就是这样了 重启网管OK了

**Comment by IKende** [comment]
2K是包括死链接，`FastHttpApi`没记错是默认30分钟清一次死连接

**Comment by nodyang** [comment]
3Q
