### ISSUE TITLE
out of max connections  demo 数据依旧上涨

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#49]
![image](https://user-images.githubusercontent.com/3090191/71759239-1f8dda00-2ee5-11ea-9d16-5c07f812a6c2.png)
![image](https://user-images.githubusercontent.com/3090191/71759246-346a6d80-2ee5-11ea-94da-2ab013edbd3a.png)
![image](https://user-images.githubusercontent.com/3090191/71759253-421ff300-2ee5-11ea-817f-698e55bd7563.png)
5分钟不到 连接上300  是不是不能映射 / 
为了解决空白 /访问 映射到别的系统的欢迎页 所产生的问题。

**Comment by nodyang** [comment]
去掉 / 正常

**Comment by IKende** [comment]
测试下来`System.Net.Http.HttpClient.GetStreamAsync`有问题，为了节省时间Bumblebee直接用这个来ping节点服务的可用性。
当正常200响应这对象反倒会不停地重新创建连接，在404状态下反而正常。所以你配了重写路由导致不是404....

**Comment by IKende** [comment]
fix v1.3.3.9

**Comment by nodyang** [comment]
3Q
