### ISSUE TITLE
是否支持SignalR

### ISSUE THREAD

**Issue by csurn** [IKende/Bumblebee#51]
你好，我在代理asp.net core SignalR站点时遇到了问题：SignalR会发送两条请求，一条http的，一条ws的，除了协议部分，url其他部分相同，如何能让路由根据协议来将请求转发给asp.net core SignalR站点？
以上
        谢谢

**Comment by IKende** [comment]
设计上不支持代理http推模式，不过支持ws代理，可以尝试对这个节点添加两个服务http://host和ws://host ，让http和websocket都转发过去，然后在路由上添加这两个服务

**Comment by csurn** [comment]
你好，感谢快速的回复。
我配置的路由是：
/IoTCenter.*
对应服务：
http://localhost:8011/
ws://localhost:8011/
在IoTCenter项目里没有转发过来的ws请求。
Bumblebee后台Log显示：
Gateway websocket 26479527156779632 ::1 GET /IoTCenter/hub process error One or more errors occurred.
我又尝试了将路由改为：ws://localhost/IoTCenter.*的形式，服务对应位：ws://localhost:8011/仍然还是不成功。
请问咱们这个网关之前是否有测试过搭配SignalR使用的情况吗？

**Comment by IKende** [comment]
组件只针对ws做过测试，并没有对`SignalR`,如果方便可以把这个sample项目放上来调试

**Comment by csurn** [comment]
你好，感谢回复。这是重新创建的只包含相关代码的测试项目，可以复现。
[BumblebeeSignalR.zip](https://github.com/IKende/Bumblebee/files/4024650/BumblebeeSignalR.zip)

**Comment by IKende** [comment]
好的谢谢，初步估计是代理connect的时候没有带上相应的ws请求头。

**Comment by csurn** [comment]
还得感谢你这个Bumblebee，就是start有点少，比之前用一个别的.net网关性能和易用性强很多。

**Comment by IKende** [comment]
测试了一下的确是代理连接没有把SignalR需要的一些信息带过去被拒绝了，需要等到下一个版本发布解决。

**Comment by IKende** [comment]
已更新到 1.3.4.6
