### ISSUE TITLE
default_request_log_to_db writer error One or more errors occurred

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#53]
default_request_log_to_db writer error One or more errors occurred. (“http:”附近有语法错误。
“xcmd”附近有语法错误。
“http:”附近有语法错误。
标签 'http' 已声明。标签名称在查询批次或存储过程内部必须唯一。
“http:”附近有语法错误。
标签 'http' 已声明。标签名称在查询批次或存储过程内部必须唯一。)@ at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Bumblebee.Logs.DBLog.OnWrite(Object state)

::ffff:27.223.178.230 get token error IDX10503: Signature validation failed. Keys tried: '[PII is hidden]'. Exceptions caught: '[PII is hidden]'. token: '[PII is hidden]'.
--

::ffff:27.223.178.230 get token error IDX10503: Signature validation failed. Keys tried: '[PII is hidden]'. Exceptions caught: '[PII is hidden]'. token: '[PII is hidden]'.
--

::ffff:27.223.178.230 get token error IDX10503: Signature validation failed. Keys tried: '[PII is hidden]'. Exceptions caught: '[PII is hidden]'. token: '[PII is hidden]'.
--

**Comment by IKende** [comment]
这个日志插件只是拼装SQL，如果有些人在URL加入一些比较特别的字符就可以导致SQL有问题

**Comment by nodyang** [comment]
有没有好的方式去杜绝。我都快让扫描的 扫奔溃了

**Comment by IKende** [comment]
http://doc.beetlex.io/#1b80181d2d20408aabb0b493936c8f7a
这里有个自己写日志的示例
