### ISSUE TITLE
BeetleX.Bumblebee.Consul 只能是一个path？

### ISSUE THREAD

**Issue by laiguorong** [IKende/Bumblebee#55]
`Dictionary<string, string> meta = new Dictionary<string, string>();
meta.Add("path", "^/home.*");
client.Agent.ServiceDeregister("api_test1").Wait();
client.Agent.ServiceDeregister("api_test2").Wait();
client.Agent.ServiceRegister(new AgentServiceRegistration
{
    Tags = new string[] { "Bumblebee" },
    Address = "192.168.2.18",
    Port = 8080,
    Name = "bumblebee_services",
    Meta = meta,
    ID = "api_test1"
}).Wait();`

meta.Add("path", "^/home.*");
只能是一个么？多个路由应该怎么处理；BeetleX.Bumblebee.Consul有源码看看么？

![image](https://user-images.githubusercontent.com/15118012/72318228-a9ecef80-36d6-11ea-8cd2-2f80aaa46e75.png)

**Comment by IKende** [comment]
插件没有开源，现在一个服务只能加到一个url下

**Comment by laiguorong** [comment]
那要怎么处理才能支持多个路由？

**Comment by IKende** [comment]
只能手动调用网关的UrlRoute调用方法配置

**Comment by laiguorong** [comment]
插件什么时候能支持一下多个路由呢？

**Comment by IKende** [comment]
更新`BeetleX.Bumblebee.Consul 1.3.4`
``` csharp
 meta.Add("path", "^/home.*;^/hello.*");
```
在设置path里，有`;`号区分多个path
