### ISSUE TITLE
超时的问题

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#56]
![image](https://user-images.githubusercontent.com/3090191/75004159-2ed0e300-54a5-11ea-909a-ef0bcfbac72e.png)
![image](https://user-images.githubusercontent.com/3090191/75004181-427c4980-54a5-11ea-9642-357815f0c161.png)
我一个域名下 挂了2个节点。但是有一个节点超时了。并没有访问另外一个节点。程序就一直卡在哪

**Comment by IKende** [comment]
现在超时是由socket自己处理，异步的情况可能时间上不可控，需要调整超时处理方式。

**Comment by IKende** [comment]
其实client端最好也做超时处理

**Comment by nodyang** [comment]
有好的解决思考吗

**Comment by IKende** [comment]
新版本的路由规则有这个配置属性`TimeOut`单位秒，默认值是0不处理，可自行在配置文件中添加这属性。
`

**Comment by wwping** [comment]
我没找到关于 TimeOut 的配置

**Comment by IKende** [comment]
这个配置只针对UrlRoute，不是全局

**Comment by wwping** [comment]
OK，找到了 
![1](https://user-images.githubusercontent.com/10977033/79036695-6df5f780-7bfd-11ea-8621-b797c7c1d114.png)

**Comment by nodyang** [comment]
> OK，找到了
> ![3](https://user-images.githubusercontent.com/10977033/79036725-b2819300-7bfd-11ea-8077-a7aef73f24e7.png)

这个挺好看的。。

**Comment by wwping** [comment]
> > OK，找到了
> > ![3](https://user-images.githubusercontent.com/10977033/79036725-b2819300-7bfd-11ea-8077-a7aef73f24e7.png)
> 
> 这个挺好看的。。

自己弄的

**Comment by nodyang** [comment]
> > > OK，找到了
> > > ![3](https://user-images.githubusercontent.com/10977033/79036725-b2819300-7bfd-11ea-8077-a7aef73f24e7.png)
> > 
> > 
> > 这个挺好看的。。
> 
> 自己弄的

可以开源吗？

**Comment by IKende** [comment]
可以啊

**Comment by wwping** [comment]
可以开源啊，不过这个用的不是作者的那个配置插件，是我仿照作者的代码自己做的一个前后端分离的，

**Comment by wwping** [comment]
> > > > OK，找到了
> > > > ![3](https://user-images.githubusercontent.com/10977033/79036725-b2819300-7bfd-11ea-8077-a7aef73f24e7.png)
> > > 
> > > 
> > > 这个挺好看的。。
> > 
> > 
> > 自己弄的
> 
> 可以开源吗？

https://github.com/wwping/Qbcode.Configuration.Api
