### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#59]
![image](https://user-images.githubusercontent.com/3090191/75825200-e0dea800-5ddf-11ea-9205-3f84f9f5487d.png)
Gateway 26558163345059819 ::ffff:39.77.149.151 GET /api/admin/gethost error Object reference not set to an instance of an object.@ at Bumblebee.Gateway.OnRequestCompleted(RequestAgent success)
![image](https://user-images.githubusercontent.com/3090191/75825369-21d6bc80-5de0-11ea-9420-50b5bed2f340.png)
最新版的网关。上个版本还没有这个问题。现在产生了大量的警告

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/75825986-6f9ff480-5de1-11ea-80f9-e766e7b81139.png)

**Comment by IKende** [comment]
新版本在这个事件处理上是有问题，已经在nuget上撤了这版，建议降级；这边的生产环境测试好后再发版本。

**Comment by IKende** [comment]
可更新到1.3.5.4

**Comment by nodyang** [comment]
谢谢哥。。
