### ISSUE TITLE
Nginx 转发到网关需要注意啥

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#60]
[图片]
![I{S1@3PB1W@682JV[0[TY}D.png](https://p.pstatp.com/origin/ff260001a76e8ad75a5b)

**Comment by nodyang** [comment]
1 FastHttpApi 可以直接绑定域名不? 试图通过配置文件的Host 提示失败
2 我们试图nginx 到网关  网关绑定dns映射的内网域名。 但是发现访问不通
[图片]

**Comment by IKende** [comment]
这个只是dns问题，这种情况你要自己网内搭建dns服务

**Comment by nodyang** [comment]
中午上线 还有是大量的警告 
![image](https://user-images.githubusercontent.com/3090191/76490598-8809b200-6466-11ea-87a0-e39472bbc415.png)
![image](https://user-images.githubusercontent.com/3090191/76490618-9657ce00-6466-11ea-8fec-a84b1600ed2f.png)
但可以取到数据。总体感觉好棒

**Comment by IKende** [comment]
其实这种情况是存在的，当路由建立了，但相关服务器状态还没完全处理好，这时请求就会有这警告出现。
