### ISSUE TITLE
1.3.6版本 IRespondingHandler 的 Exeucte应该是写错了

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#65]
![6](https://user-images.githubusercontent.com/10977033/78006777-fcea5080-736f-11ea-8620-395154ec61fa.png)

**Comment by IKende** [comment]
是的写错了

**Comment by wwping** [comment]
这个网关怎么做跨域啊，我没找到可以跨域的配置或者插件

**Comment by IKende** [comment]
这个暂不支持

**Comment by wwping** [comment]
跨域插件我写好了
