### ISSUE TITLE
Bumblebee最新版本 ab并发测试超时了

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#68]
下载BumblebeeVSOcelot 进行ab测试
在nuget更新 Bumblebee 版本之后就出现了问题，nuget版本在 1.2.2之前正常运行，之后的版本出现错误，更严重的是直接超时
# nuget
![1](https://user-images.githubusercontent.com/10977033/78116005-39807f80-7436-11ea-8f6d-e3151b556785.png)
# 更新到1.2.2以后的版本之后
![2](https://user-images.githubusercontent.com/10977033/78116052-4f8e4000-7436-11ea-977d-b0516f5dbf43.png)
# 我的项目用的是 1.3.6版本
![3](https://user-images.githubusercontent.com/10977033/78116197-89f7dd00-7436-11ea-849a-8564e3e97977.png)

不明白是什么问题

**Comment by IKende** [comment]
建议单独引用新版本,看一下运行的版本号,github上的代码已经修复这错误
https://github.com/IKende/Bumblebee/blob/master/Bumblebee/Gateway.cs
``` csharp
 public void RequestIncrementCompleted(HttpRequest request, int code, long time, Servers.ServerAgent server = null)
        {
            HttpServer.IncrementResponsed(request, null, time, code, null);
            if (StatisticsEnabled)
            {
                Statistics.Add(code, time);
                if (Statistical(request))
                    Routes.UrlStatisticsDB.Add(code, time, server, request);
            }
            try
            {
                RequestIncrement?.Invoke(this, new EventRequestIncrementArgs(request, code, time, server));
            }
            catch (Exception e_)
            {
                if (HttpServer.EnableLog(LogType.Error))
                {
                    HttpServer.Log(LogType.Error, $"Gateway {request.ID} {request.RemoteIPAddress} {request.Method} {request.Url} request increment event error {e_.Message}@{e_.StackTrace}");
                }
            }
        }
```

**Comment by wwping** [comment]
那我下载github上的代码来试试

**Comment by wwping** [comment]
这是目前使用的版本 
```
 public void RequestIncrementCompleted(HttpRequest request, int code, long time, Servers.ServerAgent server = null)
        {
            HttpServer.IncrementResponsed(request, null, time, code, null);
            if (StatisticsEnabled)
            {
                Statistics.Add(code, time);
                if (Statistical(request))
                    Routes.UrlStatisticsDB.Add(code, time, server, request);
            }
            try
            {
                RequestIncrement?.Invoke(this, new EventRequestIncrementArgs(request, code, time, server));
            }
            catch (Exception e_)
            {
                if (HttpServer.EnableLog(LogType.Error))
                {
                    HttpServer.Log(LogType.Error, $"Gateway {request.ID} {request.RemoteIPAddress} {request.Method} {request.Url} request increment event error {e_.Message}@{e_.StackTrace}");
                }
            }
        }
```

**Comment by wwping** [comment]
超时的问题可以得到解决吗  ab测试一直不成功

**Comment by wwping** [comment]
![2](https://user-images.githubusercontent.com/10977033/78218348-38ac2400-74f0-11ea-9ec1-1f9eb17e540e.png)
![34](https://user-images.githubusercontent.com/10977033/78218402-5083a800-74f0-11ea-9c57-d9a9475fcee9.png)
![1](https://user-images.githubusercontent.com/10977033/78218412-52e60200-74f0-11ea-9a78-930ff497a873.png)
![34](https://user-images.githubusercontent.com/10977033/78218443-5d080080-74f0-11ea-924e-42a3bac48d83.png)

**Comment by wwping** [comment]
![00](https://user-images.githubusercontent.com/10977033/78219063-69408d80-74f1-11ea-9bb6-04d2dda857b7.png)
![11](https://user-images.githubusercontent.com/10977033/78219079-6fcf0500-74f1-11ea-8cfe-c6db20cc791c.png)
![22](https://user-images.githubusercontent.com/10977033/78219094-73fb2280-74f1-11ea-81ee-0e986bfc079e.png)
![33](https://user-images.githubusercontent.com/10977033/78219109-78274000-74f1-11ea-99db-1f643184d31a.png)

**Comment by wwping** [comment]
弄出结果了， 可能是版本冲突的原因，因为装了几个插件，还有两个自己写的插件，可能导致了各版本不一致，
## 解决办法
先在主项目项目中安装 Bumblebee   然后再安装其它的插件，如果有冲突，则需要更新到与主项目中一致的Bumblebee  版本， beetlex版本不一致也更新一下。

**Comment by nodyang** [comment]
> 弄出结果了， 可能是版本冲突的原因，因为装了几个插件，还有两个自己写的插件，可能导致了各版本不一致，
> 
> ## 解决办法
> 先在主项目项目中安装 Bumblebee 然后再安装其它的插件，如果有冲突，则需要更新到与主项目中一致的Bumblebee 版本， beetlex版本不一致也更新一下。

厉害了

**Comment by wwping** [comment]
IRespondingHandler 没被执行，无法向 response写入自定义headers  比如 跨域

**Comment by IKende** [comment]
Responding的response并不能接管后台服务器响应的response,具体可以看requestagent的代码

**Comment by wwping** [comment]
那无法了，不知道怎么写入自定义hander
