### ISSUE TITLE
网关遇到问题好难讨论啊~有QQ群吗 

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#69]
有QQ群吗

**Comment by nodyang** [comment]
> 有QQ群吗
好像潘哥在写自己的聊天室。敬请期待

**Comment by wwping** [comment]
你好，你有遇到 ab测试超时吗，我一直超时，好烦恼

**Comment by nodyang** [comment]
> 你好，你有遇到 ab测试超时吗，我一直超时，好烦恼

你更新版本试试。我记得这个问题作者解决了

**Comment by wwping** [comment]
我使用了 github上的最新版本，好像是1.3.5.2

**Comment by wwping** [comment]
我发在  #68 的那个

**Comment by wwping** [comment]
好希望老大建个QQ群呀
