### ISSUE TITLE
有没有可能结合consul

### ISSUE THREAD

**Issue by yuzd** [IKende/Bumblebee#7]
比如说 微服务A
注册了 127.0.0.1
            到了 consul。。
bumblebee同步过来访问 http://getwathost:xxx:/a 访问到 127.0.0.1
微服务又上线了1台机器B 127.0.0.2 到 consul
bumblebee同步过来访问 http://getwathost:xxx:/a 会负载均衡到127.0.0.1 和 127.0.0.2

**Comment by IKende** [comment]
你是想bumblebee，通过consul自动添加负载配置？

**Comment by yuzd** [comment]
是的。大概就是这个意思。如果配置文件里面配置下就能达到这样的效果就太爽了

**Comment by IKende** [comment]
这个功能实现不是很困难，bumblebee的`Gateway.SetServer`是支持运行时动态更新的，其实外加个定时器来获取consul数据调用这方法即可，先打个标签，后继找时间外加这一功能。

**Comment by IKende** [comment]
[BeetleX.Bumblebee.Consul](https://www.nuget.org/packages/BeetleX.Bumblebee.Consul/)

**Comment by yuzd** [comment]
666 越来越牛了
