### ISSUE TITLE
一次测试的奇怪结果，不明所以

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#71]
比较奇怪的结果，多出了一些请求次数，并且有一些次数没有携带我设置的 header  requestid

# 网关版本信息
![11](https://user-images.githubusercontent.com/10977033/78322986-07406080-75a3-11ea-80c5-526c3f24ec0e.png)

# 网关代码
![0](https://user-images.githubusercontent.com/10977033/78322784-4d48f480-75a2-11ea-9048-6c503979db84.png)

# api代码
![2](https://user-images.githubusercontent.com/10977033/78322790-50dc7b80-75a2-11ea-81fa-56a23ad72b25.png)

# apache ab请求结果
![1](https://user-images.githubusercontent.com/10977033/78322792-54700280-75a2-11ea-9d71-f8177732b4a7.png)

# 结果数据
![3](https://user-images.githubusercontent.com/10977033/78322796-56d25c80-75a2-11ea-96fc-65abfb0c8bd8.png)

**Comment by IKende** [comment]
建议你用client发起的数据结合响应数据做一个测试验证.
