### ISSUE TITLE
承接 response 的header 的问题

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#74]
经过一些测试，存在一些疑惑，不知是否作者有其它考虑
#### 正常的
- 在路由聚合中  ， 添加一些信息可以被添加到 请求的 respone中，
- 在 BeetleX.FastHttpApi.ControllerAttribute 定义的控制器中的请求也可以正常运行
#### 失败的
- 但是在正常的代理中无法正常返回添加的 header信息

### 导致的问题
- 1，1.3.6.7版本中新增的 cors 的 headers  在 **路由聚合** 中不起作用
- 2，在 BeetleX.FastHttpApi.ControllerAttribute 定义的控制器中也不起作用

### 思考
- 那么，是否可以在代理下游请求时  可以将 EventRequestingArgs 的 所携带的  Response.Header 输出到最终相应的 respone 的header中呢

**Comment by IKende** [comment]
严格来说聚合并没有走网关的代理通道，是插件自己发起请求整合后在当前response输出。
正常代理的所有头都是由节点服务来输出，也不是不能定义，可查看`IHeaderWritingHandler`的设计。

**Comment by wwping** [comment]
不修改源码的前提下，没有找到方法可以在正常代理的respone中增加一些header

**Comment by wwping** [comment]
我有个插件 实现了 IHeaderWritingHandler 接口。但是Execute(EventHeaderWritingArgs e)没有被执行

**Comment by wwping** [comment]
![1](https://user-images.githubusercontent.com/10977033/79239465-3019fd00-7ea3-11ea-94cd-025af0680e79.png)
![2](https://user-images.githubusercontent.com/10977033/79239534-41fba000-7ea3-11ea-89b1-b6434d2a7e98.png)
