### ISSUE TITLE
服务器状态问题

### ISSUE THREAD

**Issue by nodyang** [IKende/Bumblebee#75]
![image](https://user-images.githubusercontent.com/3090191/79709930-0bd07d00-82f6-11ea-93cd-3fbb5945a413.png)
![image](https://user-images.githubusercontent.com/3090191/79709938-12f78b00-82f6-11ea-81e0-346485ac6a7a.png)
1 上午对01 编号的服务器进行维护 但网关的列表还是显示在线
2  01的依旧在接受请求。理想状态 我希望02进行接受  
3 对01的服务器一定超过3次以上的请求。但依旧没有断开。
4 也设置了timeout 时间

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/79710349-54d50100-82f7-11ea-8a49-017ef5159c45.png)
重启以后状态正常。但收到请求会。都变成了联通的状态 但01服务器还处于关闭状态
![image](https://user-images.githubusercontent.com/3090191/79710495-bac18880-82f7-11ea-9ee5-8a50b435e7e9.png)

**Comment by IKende** [comment]
这情况可能是对应域名的IP地方发生变更了

**Comment by nodyang** [comment]
我下次做了测试。测试环境全是IP加端口 
![image](https://user-images.githubusercontent.com/3090191/79948412-67416d00-84a6-11ea-8800-9865cd9cd4e2.png)
效果依旧显示可以访问的。 85服务是物理关闭的

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/79949619-68739980-84a8-11ea-9397-a92f258eb98c.png)
只要有访问。他神奇的变成了绿色了
