### ISSUE TITLE
网关有两个插件目前无法使用

### ISSUE THREAD

**Issue by gwhzh21** [IKende/Bumblebee#83]
BeetleX     Version [1.5.1.7]
 FastHttpApi Version [1.8.5.2]
 Bumblebee   Version [1.3.7.0]

gateway = new Gateway();
                gateway.HttpOptions(o =>
                {
                    o.Port = 10080;
                    o.LogToConsole = true;
                    o.LogLevel = BeetleX.EventArgs.LogType.Error;
                });
                gateway.Open();
                gateway.LoadPlugin(typeof(Bumblebee.Configuration.Management).Assembly,
              typeof(Bumblebee.Caching.default_request_cached_reader).Assembly);

有两个插件运行不了

typeof(Bumblebee.Logs.FileLog).Assembly)提示
Unhandled exception. System.MissingMethodException: Method not found: 'Void BeetleX.FastHttpApi.HttpApiServer.Log(BeetleX.EventArgs.LogType, System.String)'.

typeof(Bumblebee.Caching.default_request_cached_reader).Assembly提示

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'Execute' in type 'Bumblebee.Caching.default_request_cached_writer' from assembly 'Bumblebee.Caching, Version=1.3.3.0, Culture=neutral, PublicKeyToken=2c66059f2575a953' does not have an implementation.

**Comment by IKende** [comment]
插件相关的已经没再更新了，没太多精力去管理这方面的东西。
