### ISSUE TITLE
转发慢的问题咨询

### ISSUE THREAD

**Issue by stonezhu870** [IKende/Bumblebee#86]
netcore 3.1 mvc 
写了一个controller，action里面读redis取值。
用postman runner，200个并发，大概10ms左右

使用了bumblebee，转发中配置了[/api/base/.*] 直接转到我的应用上，
用postman runner跑，最慢的有150ms，最少的15ms左右，是否不均匀。

bumblebee的版本为1.4.2.3。
环境是：应用在物理机上，bumblebee在本机的docker中。

请问我改从哪些方面检查和查找原因？

**Comment by IKende** [comment]
测试环境需要调整一下，网关承载的网络io量会翻倍，docker上的网络io开销比较大。
建议反过来把网关部署到物理机上进行测试。

**Comment by stonezhu870** [comment]
> 测试环境需要调整一下，网关承载的网络io量会翻倍，docker上的网络io开销比较大。
> 建议反过来把网关部署到物理机上进行测试。

的确拿出来就正常了很多。

刚上手docker，我的理解这种只是做了端口转发，这点流量应该不至于会影响网络io才对，如果将来，gateway和接口应用都部署在docker中，难道就要面临这种性能损失？

**Comment by IKende** [comment]
docker这种对IO的影响还是很大的，不过到云环境没这么严重，毕竟标配都是10Gb模块，网络虚拟化支持也好

**Comment by stonezhu870** [comment]
感谢解答
