### ISSUE TITLE
Gateway配置完成后，无法进行转发

### ISSUE THREAD

**Issue by Vincentyiu** [IKende/Bumblebee#88]
网关配置中：
- Server配置正确，绿灯可进行访问

- Routes配置正确，绿灯可进行访问
访问被转发地址报错如下：

16:26:15 | Warring | Gateway 26930759088472394 ::ffff:127.0.0.1 GET /basicinfo/index.html error Specified argument was out of the range of valid values. (Parameter 'port')

16:26:15 | Warring | gateway 26930759088472394 ::ffff:127.0.0.1 GET /basicinfo/index.html -> :-1 completed code 582 use time:1ms

16:26:15 | Error | gateway [26930759088472394] request :-1 error Specified argument was out of the range of valid values. (Parameter 'port')@Specified argument was out of the range of valid values. (Parameter 'port') status Requesting

**Comment by IKende** [comment]
`16:26:15 | Warring | gateway 26930759088472394 ::ffff:127.0.0.1 GET /basicinfo/index.html -> :-1 completed code 582 use time:1ms`
看样子是服务添加的地址有问题引起处理错误

**Comment by Vincentyiu** [comment]
> `16:26:15 | Warring | gateway 26930759088472394 ::ffff:127.0.0.1 GET /basicinfo/index.html -> :-1 completed code 582 use time:1ms`
> 看样子是服务添加的地址有问题引起处理错误

嗯，仔细看了json文件，确实是配置问题，http没有打在配置地址上造成的问题，感谢回复了
