### ISSUE TITLE
JWT统一认证配置

### ISSUE THREAD

**Issue by Vincentyiu** [IKende/Bumblebee#89]
1.4.5.2网关通过安装使用可以正常使用JWT认证功能，但在Nuget引用后无法对网关插件default_jwt_auth进行配置
`gateway.LoadPlugin(typeof(Bumblebee.Configuration.Management).Assembly);`

**Comment by IKende** [comment]
这功能不是Bumblebee的内部功能，它都是外置扩展的。 可以看一下这些使用者是如何扩展的。

https://github.com/IKende/Bumblebee/issues/85

https://github.com/IKende/Bumblebee/issues/82

https://github.com/IKende/Bumblebee/issues/79

**Comment by Vincentyiu** [comment]
感谢提供的信息
