### ISSUE TITLE
根据域名进行区分的转发

### ISSUE THREAD

**Issue by IKende** [IKende/Bumblebee#9]
例如： 服务器 192.168.2.3 IIS: 用户接口 api1.server.com:80 组织接口 api2.server.com:80
配置后只会转发到其中一个接口。nginx也是不能通过域名区分。

**Comment by IKende** [comment]
组件对同一个URL接口，来源于不同域名可以制定不同的转发，URL制定如下:
`api1.server.com|/user.*`
或
`api2.server.com|/user.*`

**Comment by eddyyuen** [comment]
这个配置是把相同url的转发到不同的server。
我的需求是几个api server部署在同一台服务器的同一个端口（例如IIS）。访问时通过域名进行区分。
但是fasthttpapi连接api server是把域名解析为IP后进行连接的。这样IIS就不能区分转发后访问的是哪一个域名，通常就会默认解析为第一个。

**Comment by IKende** [comment]
@eddyyuen 
按道理不存在这情况，Bumblebee转发的过程会带上访问Bumblebee的host头信息

**Comment by eddyyuen** [comment]
> @eddyyuen
> 按道理不存在这情况，Bumblebee转发的过程会带上访问Bumblebee的host头信息

是我的逻辑错了。因为访问的两个不同域名的接口，正因为带上了host头信息，IIS只认这个host。

**Comment by IKende** [comment]
@eddyyuen 
是你想host信息是你配置服务的域名而不是请求的域名？要是这样只能通过代码扩展才能实现，在0.9之前的版本其实可以通过AgentRequesting事件中设置，在事件里得到当前agentserver的配置的host,然后设置到request.Header中即可。
新版本看
https://github.com/IKende/Bumblebee/blob/master/Bumblebee.BaseSample/Program.cs
