### ISSUE TITLE
突然间报ssl错误

### ISSUE THREAD

**Issue by wwping** [IKende/Bumblebee#91]
近半年时间没有更新过代码了，今天突然服务崩溃，查看日志发现以下信息
1，不开启ssl的时候没问题，开启ssl后请求几次服务后服务就停止运行了
![QQ图片20201206211923](https://user-images.githubusercontent.com/10977033/101282785-f3eb3200-37ce-11eb-8c9b-ae8686395e56.png)

**Comment by wwping** [comment]
![1](https://user-images.githubusercontent.com/10977033/101282896-81c71d00-37cf-11eb-9605-81564f0dfaa4.png)

**Comment by wwping** [comment]
![2](https://user-images.githubusercontent.com/10977033/101282977-f26e3980-37cf-11eb-8e8f-24ee82a1deaf.png)

**Comment by IKende** [comment]
这是一个bug来的，ssl触发的未知异常（触发机率低），更新一下beetlex吧

**Comment by IKende** [comment]
https://github.com/IKende/BeetleX/issues/57

**Comment by wwping** [comment]
好的，多谢

**Comment by wwping** [comment]
我看了下beetlex的版本，发现是用的1.5.1.7
![12](https://user-images.githubusercontent.com/10977033/101299938-d7063b80-386e-11eb-858b-8c31986111aa.png)
